### ISSUE TITLE
Trouble with amiga.lib?

### ISSUE THREAD

**Issue by reinauer** [cnvogelg/romdisk#3]
My vlink does not seem to like my _ExpansionBase

I'm aware this is probably a toolchain issue, but I could not find a good solution on the internet so far.

```
/opt/amiga/bin/vlink -bamigahunk -x -Bstatic -Cvbcc -nostdlib -lamiga "BUILD/obj_dbg/device.o" "BUILD/obj_dbg/disk.o" "BUILD/obj_dbg/mydev.o" "BUILD/obj_dbg/worker.o" "BUILD/obj_dbg/unpack.o" "BUILD/obj_dbg/debug.o" "BUILD/obj_dbg/boot.o" "BUILD/obj_dbg/rnc.o" "BUILD/obj_dbg/inflate.o" "BUILD/obj_dbg/lz4.o" "BUILD/obj_dbg/diag.o" "BUILD/obj_dbg/end.o"   -lvcs  -L/opt/amiga/m68k-amigaos/vbcc/lib -L/opt/amiga/m68k-amigaos/vbcc/include -l amiga -o BUILD/romdisk.device_dbg 

amiga.lib(AddBootNode.o): In "_AddBootNode":
Error 21: amiga.lib(AddBootNode.o) (CODE+0x4): Reference to undefined symbol _ExpansionBase.
amiga.lib(MakeDosNode.o): In "_MakeDosNode":
Error 21: amiga.lib(MakeDosNode.o) (CODE+0x4): Reference to undefined symbol _ExpansionBase.
amiga.lib(AddConfigDev.o): In "_AddConfigDev":
Error 21: amiga.lib(AddConfigDev.o) (CODE+0x4): Reference to undefined symbol _ExpansionBase.
amiga.lib(AllocConfigDev.o): In "_AllocConfigDev":
Error 21: amiga.lib(AllocConfigDev.o) (CODE+0x4): Reference to undefined symbol _ExpansionBase.
```

I believe this is a bebbo toolchain from February 2020

```
vbcc V0.9f (c) in 1995-2017 by Volker Barthelmann
vbcc code-generator for m68k/ColdFire V1.11 (c) in 1995-2017 by Volker Barthelmann
```

```
vlink V0.16c (c)1997-2019 by Frank Wille
build date: Feb 21 2020, 18:00:54
```

**Comment by reinauer** [comment]
Ok, just rebuilt the latest bebbo toolchain and reproduced the issue.

I also did the following in order to create a reasonable looking include path for
/opt/m68k-amigaos/os-include 

```
cd /opt
sudo ln -s amiga/m68k-amigaos
cd m68k-amigaos
ln -s ndk-include os-include
```

**Comment by cnvogelg** [comment]
The above error messages occur if the `proto` folder of the NDK does not support VBCC's inlining mechanism. In this case the library calls are regular c exports that are fulfilled by `amiga.lib`, but they need the missing `_ExpansionBase` symbol (and they wouldn't work for ROMable code).

In the old toolchain I used the NDK was patched accordingly and the `proto` files there were re-generated to support many compilers including VBCC.

You can fix the NDK manually by copying the `proto` files from `$VBCC/targets/m68k-amigaos/include/proto`.
Do not replace the whole `proto` folder as some files are not available in the VBCC folder, namely `alib.h`.

**Comment by cnvogelg** [comment]
Update: in a43f270 I fixed the build so you can use a recent VBCC installation with an unmodified NDK...

**Comment by reinauer** [comment]
Awesome, thank you! I can confirm that both approaches worked for me.
